# Override subchart values with working repositories
conference-app:
  postgresql:
    image:
      repository: "bitnamisecure/postgresql"
      tag: "latest"
  kafka:
    image:
      repository: "bitnamicharts/kafka"
      tag: "32.4.3"
  redis:
    image:
      repository: "bitnamisecure/redis"
      tag: "latest"
  install:
    infrastructure: true
    ingress: true
