# Use fixed frontend image with proper template values
conference-app:
  postgresql:
    image:
      repository: "bitnamisecure/postgresql"
      tag: "latest"
  redis:
    image:
      repository: "bitnamisecure/redis"
      tag: "latest"
  kafka:
    image:
      repository: "bitnamilegacy/kafka"
      tag: "4.0"
  services:
    registry: "localhost/salaboy"
    frontend:
      image: "frontend-go"
      imagePullPolicy: "Never"
    tag: "v1.0.0"
    debug: true
  install:
    infrastructure: true
    ingress: true