# Override subchart values with correct repositories
conference-app:
  postgresql:
    image:
      repository: "bitnamisecure/postgresql"
      tag: "latest"
  kafka:
    image:
      repository: "bitnamicharts/kafka"
      tag: "latest"
  redis:
    image:
      repository: "bitnamisecure/redis"
      tag: "latest"
  install:
    infrastructure: true
    ingress: true